controller_server:
  ros__parameters:
    controller_plugin: "controller_plugins::PurePursuitController"
    cmd_vel_topic: "/cmd_vel" # Must be of type geometry_msgs/Twist
    odom_topic: "/odom" # Must be of type nav_msgs/Odometry
    velocity_update_frequency: 0.5 # Seconds, time betwee n querying controller plugin for next velocity