planner_server:
  ros__parameters:
    planner_plugin: "planner_plugins::AstarPlanner" 
    odom_topic: "/odom" # Must be of type nav_msgs/Odometry
    isolate_path_planner: false # When set to true, planner_server doesn't call the follow_path action and instead publishes poses from the calculated path to the navigate_to_goal feedback topi
controller_server:
  ros__parameters:
    controller_plugin: "controller_plugins::PurePursuitController"
    cmd_vel_topic: "/joy_cmd_vel" # Must be of type geometry_msgs/Twist
    odom_topic: "/odom" # Must be of type nav_msgs/Odometry
    velocity_update_frequency: 0.01 # Seconds, time between querying controller plugin for next velocity
goal_selection:
  ros__parameters:
    odom_topic: "/odom" # Must be of type nav_msgs/Odometry
    gps_coords_topic: "/gps_coords" # Must be of type sensor_msgs/NavSatFix
    navigation_retry_frequency: 0.5 # Seconds, time between navigation success/failure and next navigation attempt
    waypoints_file_name: "waypoints.json" # Assumed to be within goal_selection/config